import test from 'node:test';
import assert from 'node:assert/strict';
import { CalendarCatchUp, CalendarScheduleKind, calendarScheduleRevision, commitCalendarOccurrence, nextCalendarOccurrence, normalizeCalendarSchedule, occurrenceId, zonedDateTimeToEpochMs } from '../src/core/calendar-schedule.js';

test('ONE_TIME resolves exact local datetime with revision-scoped stable occurrence identity', () => { const schedule = normalizeCalendarSchedule({ kind: 'ONE_TIME', date: '2026-09-19', time: '22:32', timeZone: 'Europe/Bratislava' }); const at = zonedDateTimeToEpochMs({ date: '2026-09-19', time: '22:32', timeZone: schedule.timeZone }); const revision = calendarScheduleRevision(schedule); assert.equal(new Date(at).toISOString(), '2026-09-19T20:32:00.000Z'); assert.equal(occurrenceId('session-a', at, revision), `session-a@${revision}@2026-09-19T20:32:00.000Z`); });
test('normalized equivalent schedules keep the same deterministic revision', () => { const a = { kind: 'daily', startDate: '2026-09-01', times: ['20:00', '08:00', '08:00:00'], timeZone: 'UTC', catchUp: 'on' }; const b = { kind: 'DAILY', startDate: '2026-09-01', times: ['08:00:00', '20:00:00'], timeZone: 'UTC', catchUp: 'ON' }; assert.equal(calendarScheduleRevision(a), calendarScheduleRevision(b)); assert.match(calendarScheduleRevision(a), /^v2-[0-9a-f]{32}$/); });
test('DAILY supports multiple times and catch-up OFF skips missed effects', () => { const schedule = { kind: CalendarScheduleKind.DAILY, startDate: '2026-09-01', times: ['08:00', '20:00'], timeZone: 'Europe/Bratislava', catchUp: CalendarCatchUp.OFF }; const next = nextCalendarOccurrence({ sessionId: 's', schedule, now: Date.parse('2026-09-19T10:00:00Z') }); assert.equal(next.localDate, '2026-09-19'); assert.equal(next.localTime, '20:00:00'); assert.equal(next.catchUp, false); });
test('DAILY catch-up OFF restart at committed boundary advances strictly past committed effect', () => { const schedule = { kind: 'DAILY', startDate: '2026-09-19', times: ['08:00', '20:00'], timeZone: 'UTC', catchUp: 'OFF' }; const at = Date.parse('2026-09-19T08:00:00Z'); const first = nextCalendarOccurrence({ sessionId: 's', schedule, now: at }); const runtime = commitCalendarOccurrence({}, first); const restarted = nextCalendarOccurrence({ sessionId: 's', schedule, runtime: structuredClone(runtime), now: at }); assert.equal(first.localTime, '08:00:00'); assert.equal(restarted.localTime, '20:00:00'); assert.ok(restarted.scheduledAt > first.scheduledAt); assert.notEqual(restarted.id, first.id); });
test('catch-up ON returns oldest uncommitted explicit occurrence', () => { const schedule = { kind: 'EXPLICIT', timeZone: 'UTC', catchUp: 'ON', occurrences: [{ date: '2026-09-19', time: '08:00' }, { date: '2026-09-19', time: '09:00' }] }; const now = Date.parse('2026-09-19T10:00:00Z'); const first = nextCalendarOccurrence({ sessionId: 's', schedule, now }); const runtime = commitCalendarOccurrence({}, first); const second = nextCalendarOccurrence({ sessionId: 's', schedule, runtime, now }); assert.equal(first.localTime, '08:00:00'); assert.equal(second.localTime, '09:00:00'); });
test('EXPLICIT durable revision cursor prevents replay after bounded history pruning and restart', () => { const occurrences = []; for (let day = 1; day <= 20; day += 1) occurrences.push({ date: `2026-01-${String(day).padStart(2, '0')}`, time: '08:00' }); const schedule = { kind: 'EXPLICIT', timeZone: 'UTC', catchUp: 'ON', occurrences }; const now = Date.parse('2026-02-01T10:00:00Z'); let runtime = {}; for (let i = 0; i < 10; i += 1) runtime = commitCalendarOccurrence(runtime, nextCalendarOccurrence({ sessionId: 's', schedule, runtime, now }), { maxHistory: 2 }); assert.equal(runtime.committedOccurrenceIds.length, 2); const restarted = structuredClone(runtime); const next = nextCalendarOccurrence({ sessionId: 's', schedule, runtime: restarted, now }); assert.equal(next.localDate, '2026-01-11'); });
test('EXPLICIT schedule edit uses an independent revision cursor', () => { const oldSchedule = { kind: 'EXPLICIT', timeZone: 'UTC', catchUp: 'ON', occurrences: [{ date: '2026-09-19', time: '09:00' }] }; const now = Date.parse('2026-09-20T10:00:00Z'); const oldOccurrence = nextCalendarOccurrence({ sessionId: 's', schedule: oldSchedule, now }); const runtime = commitCalendarOccurrence({}, oldOccurrence); const edited = { ...oldSchedule, occurrences: [{ date: '2026-09-18', time: '09:00' }] }; const next = nextCalendarOccurrence({ sessionId: 's', schedule: edited, runtime, now }); assert.ok(next); assert.notEqual(next.revision, oldOccurrence.revision); assert.equal(next.localDate, '2026-09-18'); });
test('DAILY catch-up reconciles arbitrary offline interval from durable watermark', () => { const schedule = { kind: 'DAILY', startDate: '2026-01-01', times: ['08:00'], timeZone: 'UTC', catchUp: 'ON' }; const now = Date.parse('2026-09-19T10:00:00Z'); const first = nextCalendarOccurrence({ sessionId: 's', schedule, now }); assert.equal(first.localDate, '2026-01-01'); const after = commitCalendarOccurrence({}, first, { maxHistory: 1 }); const second = nextCalendarOccurrence({ sessionId: 's', schedule, runtime: after, now }); assert.equal(second.localDate, '2026-01-02'); });
test('schedule edit gets a new revision and does not inherit old reconciliation watermark', () => { const oldSchedule = { kind: 'DAILY', startDate: '2026-09-01', times: ['20:00'], timeZone: 'UTC', catchUp: 'ON' }; const now = Date.parse('2026-09-19T22:00:00Z'); const oldOccurrence = nextCalendarOccurrence({ sessionId: 's', schedule: oldSchedule, now }); const runtime = commitCalendarOccurrence({}, oldOccurrence); const edited = { ...oldSchedule, times: ['08:00'] }; const next = nextCalendarOccurrence({ sessionId: 's', schedule: edited, runtime, now }); assert.notEqual(next.revision, oldOccurrence.revision); assert.equal(next.localDate, '2026-09-01'); assert.equal(next.localTime, '08:00:00'); });
test('timezone edit with same UTC instant has distinct occurrence identity', () => { const utc = { kind: 'ONE_TIME', date: '2026-09-19', time: '08:00', timeZone: 'UTC', catchUp: 'ON' }; const bratislava = { kind: 'ONE_TIME', date: '2026-09-19', time: '10:00', timeZone: 'Europe/Bratislava', catchUp: 'ON' }; const now = Date.parse('2026-09-19T09:00:00Z'); const first = nextCalendarOccurrence({ sessionId: 's', schedule: utc, now }); const runtime = commitCalendarOccurrence({}, first); const second = nextCalendarOccurrence({ sessionId: 's', schedule: bratislava, runtime, now }); assert.equal(first.scheduledAt, second.scheduledAt); assert.notEqual(first.id, second.id); });
test('restart after edit preserves both revision cursors and resumes edited revision', () => { const firstSchedule = { kind: 'DAILY', startDate: '2026-09-01', times: ['08:00'], timeZone: 'UTC', catchUp: 'ON' }; const edited = { ...firstSchedule, times: ['09:00'] }; const now = Date.parse('2026-09-03T12:00:00Z'); let runtime = commitCalendarOccurrence({}, nextCalendarOccurrence({ sessionId: 's', schedule: firstSchedule, now })); runtime = commitCalendarOccurrence(runtime, nextCalendarOccurrence({ sessionId: 's', schedule: edited, runtime, now })); const next = nextCalendarOccurrence({ sessionId: 's', schedule: edited, runtime: structuredClone(runtime), now }); assert.equal(Object.keys(runtime.reconciledThroughByRevision).length, 2); assert.equal(next.localDate, '2026-09-02'); assert.equal(next.localTime, '09:00:00'); });
test('revision cursor state is bounded while unresolved old revision is retained', () => { const now = Date.parse('2026-09-20T12:00:00Z'); let runtime = {}; let protectedRevision = null; for (let i = 0; i < 8; i += 1) { const schedule = { kind: 'DAILY', startDate: '2026-09-01', times: [`${String(i + 1).padStart(2, '0')}:00`], timeZone: 'UTC', catchUp: 'ON' }; const occurrence = nextCalendarOccurrence({ sessionId: 's', schedule, runtime, now }); if (i === 1) protectedRevision = occurrence.revision; runtime = commitCalendarOccurrence({ ...runtime, unresolvedOccurrenceRevisions: protectedRevision ? [protectedRevision] : [] }, occurrence, { maxRevisionCursors: 3 }); } assert.ok(Object.keys(runtime.reconciledThroughByRevision).length <= 3); assert.ok(runtime.reconciledThroughByRevision[protectedRevision] != null); assert.ok(runtime.reconciledThroughByRevision[runtime.recurrenceRevision] != null); });
test('DAILY far-future startDate is not truncated by lookahead window', () => { const schedule = { kind: 'DAILY', startDate: '2030-01-01', times: ['08:00'], timeZone: 'UTC', catchUp: 'OFF' }; const next = nextCalendarOccurrence({ sessionId: 's', schedule, now: Date.parse('2026-09-19T10:00:00Z') }); assert.equal(next.localDate, '2030-01-01'); });
test('revision watermark prevents replay even after bounded identity history prunes old IDs', () => { const schedule = { kind: 'DAILY', startDate: '2026-01-01', times: ['08:00'], timeZone: 'UTC', catchUp: 'ON' }; const now = Date.parse('2026-02-01T10:00:00Z'); let runtime = {}; for (let i = 0; i < 10; i += 1) runtime = commitCalendarOccurrence(runtime, nextCalendarOccurrence({ sessionId: 's', schedule, runtime, now }), { maxHistory: 2 }); const next = nextCalendarOccurrence({ sessionId: 's', schedule, runtime, now }); assert.equal(next.localDate, '2026-01-11'); assert.equal(runtime.committedOccurrenceIds.length, 2); });
test('explicit occurrence list is sorted and rejects duplicate local occurrence', () => { const schedule = normalizeCalendarSchedule({ kind: 'EXPLICIT', timeZone: 'UTC', occurrences: [{ date: '2026-09-20', time: '09:00' }, { date: '2026-09-19', time: '09:00' }] }); assert.equal(schedule.occurrences[0].date, '2026-09-19'); assert.throws(() => normalizeCalendarSchedule({ kind: 'EXPLICIT', timeZone: 'UTC', occurrences: [{ date: '2026-09-19', time: '09:00' }, { date: '2026-09-19', time: '09:00:00' }] }), /duplicate occurrence/); });
test('timezone conversion follows DST and rejects spring-forward gaps and fall-back ambiguity', () => { const winter = zonedDateTimeToEpochMs({ date: '2026-01-15', time: '09:00', timeZone: 'Europe/Bratislava' }); const summer = zonedDateTimeToEpochMs({ date: '2026-07-15', time: '09:00', timeZone: 'Europe/Bratislava' }); assert.equal(new Date(winter).toISOString(), '2026-01-15T08:00:00.000Z'); assert.equal(new Date(summer).toISOString(), '2026-07-15T07:00:00.000Z'); assert.throws(() => zonedDateTimeToEpochMs({ date: '2026-03-29', time: '02:30', timeZone: 'Europe/Bratislava' }), /does not exist/); assert.throws(() => zonedDateTimeToEpochMs({ date: '2026-10-25', time: '02:30', timeZone: 'Europe/Bratislava' }), /ambiguous/); assert.throws(() => normalizeCalendarSchedule({ kind: 'EXPLICIT', timeZone: 'Europe/Bratislava', occurrences: [{ date: '2026-10-25', time: '02:30' }] }), /ambiguous/); });


test('INTERVAL produces deterministic elapsed-time occurrences from an exact local anchor', () => {
  const schedule = {
    kind: 'INTERVAL',
    timeZone: 'Europe/Bratislava',
    catchUp: 'OFF',
    startDate: '2026-09-25',
    startTime: '04:00',
    intervalSeconds: 5 * 60 * 60,
  };
  const normalized = normalizeCalendarSchedule(schedule);
  assert.equal(normalized.startTime, '04:00:00');
  const firstAt = zonedDateTimeToEpochMs({ date: '2026-09-25', time: '04:00', timeZone: 'Europe/Bratislava' });
  const before = nextCalendarOccurrence({ sessionId: 'interval', schedule, now: firstAt - 1 });
  assert.equal(before.scheduledAt, firstAt);
  const later = nextCalendarOccurrence({ sessionId: 'interval', schedule, now: firstAt + 1 });
  assert.equal(later.scheduledAt, firstAt + 5 * 60 * 60 * 1000);
  assert.equal(later.catchUp, false);
});

test('INTERVAL catch-up ON returns each missed occurrence in chronological order', () => {
  const start = Date.parse('2026-09-25T04:00:00Z');
  const schedule = { kind: 'INTERVAL', timeZone: 'UTC', catchUp: 'ON', startDate: '2026-09-25', startTime: '04:00', intervalSeconds: 3600 };
  const now = Date.parse('2026-09-25T07:30:00Z');
  const first = nextCalendarOccurrence({ sessionId: 'interval', schedule, now });
  assert.equal(first.scheduledAt, start);
  assert.equal(first.catchUp, true);
  const runtime = commitCalendarOccurrence({}, first);
  const second = nextCalendarOccurrence({ sessionId: 'interval', schedule, runtime, now });
  assert.equal(second.scheduledAt, start + 3600_000);
  assert.equal(second.catchUp, true);
});

test('INTERVAL maxOccurrences exhausts without fabricating another occurrence', () => {
  const schedule = { kind: 'INTERVAL', timeZone: 'UTC', catchUp: 'ON', startDate: '2026-09-25', startTime: '04:00', intervalSeconds: 60, maxOccurrences: 2 };
  const now = Date.parse('2026-09-25T05:00:00Z');
  const first = nextCalendarOccurrence({ sessionId: 'interval', schedule, now });
  let runtime = commitCalendarOccurrence({}, first);
  const second = nextCalendarOccurrence({ sessionId: 'interval', schedule, runtime, now });
  runtime = commitCalendarOccurrence(runtime, second);
  assert.equal(nextCalendarOccurrence({ sessionId: 'interval', schedule, runtime, now }), null);
});
