import test from 'node:test';import assert from 'node:assert/strict';import {EventEmitter} from 'node:events';import {PassThrough} from 'node:stream';import {McpStdioBridge,normalizeMcpCommandRegistry} from '../companion/native-host/mcp-stdio-bridge.mjs';import {createNativeMcpTransportFactory} from '../src/core/native-companion.js';
const registry={schemaVersion:1,commands:[{commandId:'approved.node.helper',executable:'node.exe',fixedArgs:['server.mjs'],cwd:null,envKeys:['MCP_ALLOWED_TOKEN']}]};
function fakeSpawn(){const child=new EventEmitter();child.stdout=new PassThrough();child.stderr=new PassThrough();child.stdin={write(text,cb){const req=JSON.parse(text);queueMicrotask(()=>child.stdout.write(JSON.stringify({jsonrpc:'2.0',id:req.id,result:{tools:[]}})+'\n'));cb?.();return true;}};child.kill=()=>child.emit('exit',0);return child;}
test('registry is strict and defaults to no arbitrary command execution',()=>{assert.deepEqual(normalizeMcpCommandRegistry({schemaVersion:1,commands:[]}).commands,[]);assert.throws(()=>normalizeMcpCommandRegistry({schemaVersion:1,commands:[{commandId:'x',executable:'x',fixedArgs:[],shell:true}]}),/invalid/);});
test('unallowlisted command fails before spawn',async()=>{let spawned=false;const bridge=new McpStdioBridge({registry,spawnImpl:()=>{spawned=true;return fakeSpawn();}});await assert.rejects(()=>bridge.request({commandId:'evil',args:[],method:'tools/list',params:{},timeoutMs:500}),/not allowlisted/);assert.equal(spawned,false);});
test('bridge sends bounded JSON-RPC and returns result',async()=>{const bridge=new McpStdioBridge({registry,spawnImpl:fakeSpawn});assert.deepEqual(await bridge.request({commandId:'approved.node.helper',args:[],envKeys:[],method:'tools/list',params:{},timeoutMs:500}),{tools:[]});});
test('child process receives only baseline plus explicitly allowlisted requested environment',async()=>{let options;const bridge=new McpStdioBridge({registry,env:{PATH:'C:\\Windows',MCP_ALLOWED_TOKEN:'allowed',UNRELATED_SECRET:'must-not-leak'},spawnImpl:(exe,args,o)=>{options=o;return fakeSpawn();}});await bridge.request({commandId:'approved.node.helper',args:[],envKeys:['MCP_ALLOWED_TOKEN'],method:'tools/list',params:{},timeoutMs:500});assert.equal(options.env.MCP_ALLOWED_TOKEN,'allowed');assert.equal(options.env.PATH,'C:\\Windows');assert.equal('UNRELATED_SECRET' in options.env,false);await assert.rejects(()=>bridge.request({commandId:'approved.node.helper',args:[],envKeys:['UNRELATED_SECRET'],method:'tools/list',params:{},timeoutMs:500}),/not allowlisted/);});
test('transport factory propagates only configured env key names and never an executable',async()=>{let payload;const client={mcpRequest:async p=>(payload=p,{ok:true}),mcpClose:async()=>({closed:true})};const factory=createNativeMcpTransportFactory(client);const transport=await factory({commandId:'approved.node.helper',args:['server.mjs'],envKeys:['MCP_ALLOWED_TOKEN'],timeoutMs:900});await transport.request('tools/call',{name:'x',arguments:{}},{invocationId:'inv-1'});assert.equal(payload.commandId,'approved.node.helper');assert.deepEqual(payload.envKeys,['MCP_ALLOWED_TOKEN']);assert.equal(payload.method,'tools/call');assert.equal(payload.invocationId,'inv-1');assert.equal('executable' in payload,false);});
test('post-write process death is explicitly ambiguous and not safe retry',async()=>{const bridge=new McpStdioBridge({registry,spawnImpl:()=>{const c=fakeSpawn();c.stdin.write=(text,cb)=>{cb?.();queueMicrotask(()=>c.emit('exit',1));return true;};return c;}});await assert.rejects(async()=>{try{await bridge.request({commandId:'approved.node.helper',args:[],envKeys:[],method:'tools/call',params:{},timeoutMs:500});}catch(e){assert.equal(e.effectMayHaveOccurred,true);assert.equal(e.safeToRetry,false);throw e;}},/closed/);});
