import test from 'node:test';
import assert from 'node:assert/strict';
import { McpProviderV1, normalizeMcpProviderConfig } from '../src/core/mcp-provider.js';
const config={schemaVersion:1,servers:[{serverId:'local.tools',enabled:true,transport:'local-stdio',commandId:'approved.node.helper',args:['server.mjs'],envKeys:[],timeoutMs:5000}]};
const invocation={schemaVersion:1,invocationId:'inv-1',toolId:'mcp/local.tools/read',providerId:'mcp/local.tools',requestedCapabilityIds:['mcp/local.tools/read'],policyDecisionId:'decision-1',arguments:{path:'a.txt'},createdAt:'2026-09-19T20:00:00.000Z',parentInvocationId:null};
const allow={schemaVersion:1,decisionId:'decision-1',invocationId:'inv-1',decision:'ALLOW',reasonCode:'OWNER_POLICY',reason:'',approvalId:null,decidedAt:'2026-09-19T20:00:01.000Z'};
const readTool={name:'read',description:'Read',inputSchema:{type:'object',properties:{path:{type:'string'}},required:['path'],additionalProperties:false},annotations:{readOnlyHint:true}};
function factory(handler){return async()=>({request:handler,close:async()=>{}});}
test('config is local-stdio only and rejects unknown/unallowlisted server metadata',()=>{assert.throws(()=>normalizeMcpProviderConfig({schemaVersion:1,servers:[{...config.servers[0],transport:'http'}]}),/local-stdio/);assert.throws(()=>normalizeMcpProviderConfig({schemaVersion:1,servers:[{...config.servers[0],command:'node.exe'}]}),/unknown field/);});
test('discovery retains bounded schema authority but grants no execution authority',async()=>{const provider=new McpProviderV1({config,transportFactory:factory(async method=>{assert.equal(method,'tools/list');return{tools:[readTool]};})});const tools=await provider.discoverTools('local.tools');assert.equal(tools[0].toolId,'mcp/local.tools/read');assert.equal(tools[0].readOnly,true);assert.equal(provider.getInputSchema(tools[0].inputSchemaRef).properties.path.type,'string');await assert.rejects(()=>provider.invoke({serverId:'local.tools',invocation,policyDecision:{...allow,decision:'DENY'}}),/explicit ALLOW/);});
test('malformed, duplicate, too-deep and oversized discovered schemas fail closed',async()=>{for(const tools of [[{name:'read',inputSchema:null}],[{name:'read',inputSchema:{type:'object'}},{name:'read',inputSchema:{type:'object'}}],[{name:'read',inputSchema:{type:'object',description:'x'.repeat(300000)}}]]){const provider=new McpProviderV1({config,transportFactory:factory(async()=>({tools}))});await assert.rejects(()=>provider.discoverTools('local.tools'),/schema|duplicate|large/i);}let deep={type:'object'};for(let i=0;i<30;i++)deep={type:'object',properties:{x:deep}};const provider=new McpProviderV1({config,transportFactory:factory(async()=>({tools:[{name:'read',inputSchema:deep}]}))});await assert.rejects(()=>provider.discoverTools('local.tools'),/deep/i);});
test('retained discovered schema mediates invocation arguments',async()=>{let method='tools/list';const provider=new McpProviderV1({config,transportFactory:factory(async(m)=>{if(m==='tools/list')return{tools:[readTool]};method=m;return{ok:true};})});await provider.discoverTools('local.tools');await assert.rejects(()=>provider.invoke({serverId:'local.tools',invocation:{...invocation,arguments:{path:7}},policyDecision:allow}),/wrong type/);await assert.rejects(()=>provider.invoke({serverId:'local.tools',invocation:{...invocation,arguments:{path:'a',secret:'x'}},policyDecision:allow}),/Unexpected/);await provider.invoke({serverId:'local.tools',invocation,policyDecision:allow});assert.equal(method,'tools/call');});
test('invoke requires exact policy/invocation binding and forwards bounded call',async()=>{let call;const provider=new McpProviderV1({config,transportFactory:factory(async(method,params,meta)=>{if(method==='tools/list')return{tools:[readTool]};call={method,params,meta};return{content:[{type:'text',text:'ok'}]};}),now:()=>Date.parse('2026-09-19T20:00:02.000Z')});await provider.discoverTools('local.tools');await assert.rejects(()=>provider.invoke({serverId:'local.tools',invocation,policyDecision:{...allow,invocationId:'inv-other'}}),/not bound/);const result=await provider.invoke({serverId:'local.tools',invocation,policyDecision:allow});assert.equal(call.method,'tools/call');assert.equal(call.params.name,'read');assert.equal(call.meta.invocationId,'inv-1');assert.equal(result.observedAt,'2026-09-19T20:00:02.000Z');});
test('invoke fails closed before discovery and for arbitrary undiscovered tools',async()=>{let calls=0;const provider=new McpProviderV1({config,transportFactory:factory(async method=>{calls++;if(method==='tools/list')return{tools:[readTool]};return{ok:true};})});await assert.rejects(()=>provider.invoke({serverId:'local.tools',invocation,policyDecision:allow}),/discovered in the current live connection/);assert.equal(calls,0);await provider.discoverTools('local.tools');const other={...invocation,toolId:'mcp/local.tools/delete',requestedCapabilityIds:['mcp/local.tools/delete']};await assert.rejects(()=>provider.invoke({serverId:'local.tools',invocation:other,policyDecision:allow}),/not present in the current discovery/);assert.equal(calls,1);});
test('requested capabilities cannot amplify the exact discovered descriptor',async()=>{const provider=new McpProviderV1({config,transportFactory:factory(async method=>method==='tools/list'?{tools:[readTool]}:{ok:true})});await provider.discoverTools('local.tools');const amplified={...invocation,requestedCapabilityIds:['mcp/local.tools/read','filesystem.write']};await assert.rejects(()=>provider.invoke({serverId:'local.tools',invocation:amplified,policyDecision:allow}),/capability not granted/);});
test('rediscovery replaces removed tool authority rather than merging it',async()=>{let round=0;const provider=new McpProviderV1({config,transportFactory:factory(async method=>{if(method==='tools/list')return{tools:++round===1?[readTool]:[]};return{ok:true};})});await provider.discoverTools('local.tools');await provider.discoverTools('local.tools');await assert.rejects(()=>provider.invoke({serverId:'local.tools',invocation,policyDecision:allow}),/not present in the current discovery/);assert.equal(provider.getInputSchema('mcp-schema/local.tools/read/input'),null);});
test('failed rediscovery clears prior executable discovery authority',async()=>{let round=0;const provider=new McpProviderV1({config,transportFactory:factory(async method=>{if(method==='tools/list'){round++;if(round===1)return{tools:[readTool]};throw Object.assign(new Error('rediscovery failed'),{safeToRetry:true});}return{ok:true};})});await provider.discoverTools('local.tools');await assert.rejects(()=>provider.discoverTools('local.tools'),/rediscovery failed/);await assert.rejects(()=>provider.invoke({serverId:'local.tools',invocation,policyDecision:allow}),/discovered in the current live connection/);assert.equal(provider.getInputSchema('mcp-schema/local.tools/read/input'),null);});
test('unallowlisted servers fail before transport creation',async()=>{let created=false;const provider=new McpProviderV1({config,transportFactory:async()=>{created=true;return{};}});await assert.rejects(()=>provider.discoverTools('evil'),/not enabled\/allowlisted/);assert.equal(created,false);});
test('ambiguous external effect invalidates discovery and is never safe retry',async()=>{const provider=new McpProviderV1({config,transportFactory:factory(async method=>{if(method==='tools/list')return{tools:[readTool]};const error=new Error('connection lost after write');error.effectMayHaveOccurred=true;error.safeToRetry=true;throw error;})});await provider.discoverTools('local.tools');await assert.rejects(async()=>{try{await provider.invoke({serverId:'local.tools',invocation,policyDecision:allow});}catch(error){assert.equal(error.code,'MCP_EFFECT_AMBIGUOUS');assert.equal(error.effectMayHaveOccurred,true);assert.equal(error.safeToRetry,false);throw error;}},/connection lost/);await assert.rejects(()=>provider.invoke({serverId:'local.tools',invocation,policyDecision:allow}),/discovered in the current live connection/);});
test('transport crash invalidates cached connection so next safe operation reconnects',async()=>{let generations=0;const provider=new McpProviderV1({config,transportFactory:async()=>{const generation=++generations;return{request:async()=>{if(generation===1){const e=new Error('crash');e.safeToRetry=true;throw e;}return{tools:[]};},close:async()=>{}};}});await assert.rejects(()=>provider.discoverTools('local.tools'),/crash/);assert.deepEqual(await provider.discoverTools('local.tools'),[]);assert.equal(generations,2);});
test('discovery preserves transport code and safe-retry/effect metadata end to end',async()=>{const provider=new McpProviderV1({config,transportFactory:factory(async()=>{const error=new Error('tools/list timed out');error.code='MCP_TIMEOUT';error.effectMayHaveOccurred=false;error.safeToRetry=true;throw error;})});await assert.rejects(async()=>{try{await provider.discoverTools('local.tools');}catch(error){assert.equal(error.code,'MCP_TIMEOUT');assert.equal(error.effectMayHaveOccurred,false);assert.equal(error.safeToRetry,true);assert.equal(error.cause?.code,'MCP_TIMEOUT');throw error;}},/timed out/);});
test('discovery never marks retry safe when transport reports possible effect',async()=>{const provider=new McpProviderV1({config,transportFactory:factory(async()=>{const error=new Error('unexpected ambiguous discovery transport');error.code='MCP_TRANSPORT_CLOSED';error.effectMayHaveOccurred=true;error.safeToRetry=true;throw error;})});await assert.rejects(async()=>{try{await provider.discoverTools('local.tools');}catch(error){assert.equal(error.effectMayHaveOccurred,true);assert.equal(error.safeToRetry,false);throw error;}},/ambiguous discovery/);});
test('discovery follows bounded pages and grants authority only after the terminal page validates',async()=>{const seen=[];const writeTool={...readTool,name:'write',annotations:{readOnlyHint:false}};const provider=new McpProviderV1({config,transportFactory:factory(async(method,params)=>{assert.equal(method,'tools/list');seen.push(params);if(params.cursor===undefined)return{tools:[readTool],nextCursor:'page-2'};assert.deepEqual(params,{cursor:'page-2'});return{tools:[writeTool]};})});const tools=await provider.discoverTools('local.tools');assert.deepEqual(seen,[{}, {cursor:'page-2'}]);assert.deepEqual(tools.map(tool=>tool.toolId),['mcp/local.tools/read','mcp/local.tools/write']);assert.equal(provider.getInputSchema('mcp-schema/local.tools/read/input').type,'object');assert.equal(provider.getInputSchema('mcp-schema/local.tools/write/input').type,'object');});
test('discovery rejects cursor cycles, page overflow, cross-page duplicates and aggregate overflow without partial authority',async()=>{let overflowPage=0;const cases=[
  async(_method,params)=>params.cursor===undefined?{tools:[readTool],nextCursor:'same'}:{tools:[],nextCursor:'same'},
  async()=>({tools:[],nextCursor:`page-${++overflowPage}`}),
  async(_method,params)=>params.cursor===undefined?{tools:[readTool],nextCursor:'second'}:{tools:[readTool]},
  async(_method,params)=>params.cursor===undefined?{tools:Array.from({length:256},(_,index)=>({...readTool,name:`read-${index}`})),nextCursor:'second'}:{tools:[{...readTool,name:'overflow'}]},
];
  for(const handler of cases){const provider=new McpProviderV1({config,transportFactory:factory(handler)});await assert.rejects(()=>provider.discoverTools('local.tools'),/cycle|page limit|duplicate|aggregate/i);assert.equal(provider.getInputSchema('mcp-schema/local.tools/read/input'),null);await assert.rejects(()=>provider.invoke({serverId:'local.tools',invocation,policyDecision:allow}),/discovered in the current live connection/);}
});
test('a malformed late discovery page clears every prior page instead of publishing partial executable authority',async()=>{let call=0;const provider=new McpProviderV1({config,transportFactory:factory(async()=>++call===1?{tools:[readTool],nextCursor:'page-2'}:{tools:[{name:'bad',inputSchema:null}]})});await assert.rejects(()=>provider.discoverTools('local.tools'),/schema/i);assert.equal(provider.getInputSchema('mcp-schema/local.tools/read/input'),null);await assert.rejects(()=>provider.invoke({serverId:'local.tools',invocation,policyDecision:allow}),/discovered in the current live connection/);});
