import test from 'node:test';
import assert from 'node:assert/strict';
import { createEmptyState, createTask, createSession, RunMode, RunState, OperationPhase } from '../../src/core/schema.js';
import { selectNextTask, advanceAfterBusy, advanceAfterVerifiedSend } from '../../src/core/scheduler.js';
import { acquireSendLease, releaseSendLease } from '../../src/core/arbiter.js';
import { reconcileStateForStartup, computeNextWake, reconcileAlarm } from '../../src/core/recovery.js';
import { beginOperation, markSubmitting, pauseSession, resumeSession, stopSession } from '../../src/core/state-machine.js';
import { StorageRepository } from '../../src/core/storage.js';
import { resolveTaskTab } from '../../src/core/tabs.js';

const task = id => createTask({ id, url:`https://chatgpt.com/c/${id}` });
const session = (n=3, opts={}) => createSession({ id:'s', name:'S', tasks:Array.from({length:n},(_,i)=>task(`t${i+1}`)), ...opts, now:0 });

test('round-robin fairness and busy skip do not consume cooldown', () => { const s=session(3); s.runState=RunState.RUNNING; assert.equal(selectNextTask(s,1000).task.id,'t1'); advanceAfterBusy(s,0,1000); assert.equal(s.nextAllowedSendAt,0); assert.equal(selectNextTask(s,1000).task.id,'t2'); });
test('verified send advances cursor and enforces session cooldown', () => { const s=session(3,{minimumSendIntervalMs:120000}); s.runState=RunState.RUNNING; advanceAfterVerifiedSend(s,0,1000); assert.equal(s.currentTaskIndex,1); assert.deepEqual(selectNextTask(s,2000),{kind:'COOLDOWN',wakeAt:121000}); assert.equal(selectNextTask(s,121000).task.id,'t2'); });
test('one-pass completes each task once', () => { const s=session(2,{runMode:RunMode.ONE_PASS,minimumSendIntervalMs:0}); s.runState=RunState.RUNNING; advanceAfterVerifiedSend(s,0,10); advanceAfterVerifiedSend(s,1,20); assert.equal(selectNextTask(s,30).kind,'COMPLETE'); });
test('profile send arbiter excludes concurrent sessions', () => { const state=createEmptyState(0); assert.equal(acquireSendLease(state,{sessionId:'a',operationId:'1',now:100}),true); assert.equal(acquireSendLease(state,{sessionId:'b',operationId:'2',now:100}),false); assert.equal(releaseSendLease(state,{sessionId:'a',operationId:'1',now:200,profileGapMs:1000}),true); assert.equal(acquireSendLease(state,{sessionId:'b',operationId:'2',now:500}),false); assert.equal(acquireSendLease(state,{sessionId:'b',operationId:'2',now:1200}),true); });
test('startup converts RUNNING and SUBMITTING into recovery/ambiguous without resend', () => { const state=createEmptyState(0); const s=session(1); s.runState=RunState.RUNNING; beginOperation(s,{operationId:'op',taskId:'t1',promptFingerprint:'fp',targetUrl:s.tasksById.t1.url,now:10}); markSubmitting(s,20); state.sessionsById.s=s; state.sessionOrder=['s']; reconcileStateForStartup(state,30); assert.equal(s.runState,RunState.RECOVERING); assert.equal(s.operation.phase,OperationPhase.AMBIGUOUS); });
test('pause/resume/stop states are authoritative', () => { const s=session(1); pauseSession(s,1); assert.equal(s.runState,RunState.PAUSED); reconcileStateForStartup({sessionsById:{s},sendArbiter:{lease:null}},2); assert.equal(s.runState,RunState.PAUSED); resumeSession(s,3); assert.equal(s.runState,RunState.RUNNING); stopSession(s,4); assert.equal(s.runState,RunState.STOPPED); });
test('storage reloads valid v1 and rejects unsupported future schema', async () => { let db={}; const chrome={storage:{local:{get:async k=>({[k]:db[k]}),set:async rec=>Object.assign(db,rec)}}}; const repo=new StorageRepository(chrome); const initial=await repo.load(); assert.equal(initial.schemaVersion,1); const saved=await repo.update(s=>{s.profile.masterPaused=true;}); assert.equal(saved.revision,1); db.autopilotState={...saved,schemaVersion:2}; await assert.rejects(()=>repo.load(),/newer extension/); });
test('tab resolver reuses valid hint and avoids duplicate creation', async () => { const state=createEmptyState(0); const t=task('x'); state.tabHintsByTaskId.x={tabId:7}; let creates=0; const chrome={tabs:{get:async id=>({id,url:t.normalizedUrl}),query:async()=>[],create:async()=>{creates++;return {id:8,url:t.normalizedUrl}}}}; const tab=await resolveTaskTab(chrome,state,'s',t); assert.equal(tab.id,7); assert.equal(creates,0); });
test('tab resolver invalidates stale hint then reuses existing exact URL', async () => { const state=createEmptyState(0); const t=task('x'); state.tabHintsByTaskId.x={tabId:7}; let creates=0; const chrome={tabs:{get:async()=>{throw new Error('gone')},query:async()=>[{id:9,url:t.normalizedUrl}],create:async()=>{creates++;}}}; const tab=await resolveTaskTab(chrome,state,'s',t); assert.equal(tab.id,9); assert.equal(creates,0); assert.equal(state.tabHintsByTaskId.x.tabId,9); });
test('alarm reconstruction derives wake from durable state', async () => { const state=createEmptyState(0); const s=session(1); s.runState=RunState.RUNNING; s.nextAllowedSendAt=5000; state.sessionsById.s=s; state.sessionOrder=['s']; const calls=[]; const chrome={alarms:{clear:async n=>calls.push(['clear',n]),create:async(n,o)=>calls.push(['create',n,o.when])}}; assert.equal(computeNextWake(state,1000),5000); await reconcileAlarm(chrome,state,1000); assert.deepEqual(calls[1],['create','autopilot-core-wake',5000]); });
