export const InteractionResult = Object.freeze({
  READY: 'READY', BUSY: 'BUSY', SENT_VERIFIED: 'SENT_VERIFIED',
  TEMPORARY_ERROR: 'TEMPORARY_ERROR', AUTH_REQUIRED: 'AUTH_REQUIRED',
  UNKNOWN_UI: 'UNKNOWN_UI', RATE_LIMITED: 'RATE_LIMITED',
  MANUAL_REVIEW_REQUIRED: 'MANUAL_REVIEW_REQUIRED'
});

export const CoreCommand = Object.freeze({
  CREATE_SESSION: 'CREATE_SESSION', UPDATE_SESSION: 'UPDATE_SESSION', DELETE_SESSION: 'DELETE_SESSION',
  START_SESSION: 'START_SESSION', PAUSE_SESSION: 'PAUSE_SESSION', RESUME_SESSION: 'RESUME_SESSION',
  STOP_SESSION: 'STOP_SESSION', GET_SNAPSHOT: 'GET_SNAPSHOT', CLEAR_LOG: 'CLEAR_LOG',
  MASTER_PAUSE: 'MASTER_PAUSE', MASTER_RESUME: 'MASTER_RESUME'
});
