export const InteractionResult = Object.freeze({
  READY: 'READY', BUSY: 'BUSY', SENT_VERIFIED: 'SENT_VERIFIED',
  INSERTED_NOT_SENT: 'INSERTED_NOT_SENT', SUBMISSION_UNCERTAIN: 'SUBMISSION_UNCERTAIN',
  TEMPORARY_ERROR: 'TEMPORARY_ERROR', AUTH_REQUIRED: 'AUTH_REQUIRED',
  UNKNOWN_UI: 'UNKNOWN_UI', RATE_LIMITED: 'RATE_LIMITED',
  MANUAL_REVIEW_REQUIRED: 'MANUAL_REVIEW_REQUIRED'
});

export const CoreCommand = Object.freeze({
  LIST_SESSIONS: 'LIST_SESSIONS', GET_SESSION: 'GET_SESSION',
  CREATE_SESSION: 'CREATE_SESSION', UPDATE_SESSION: 'UPDATE_SESSION', DELETE_SESSION: 'DELETE_SESSION', DUPLICATE_SESSION: 'DUPLICATE_SESSION',
  START_SESSION: 'START_SESSION', PAUSE_SESSION: 'PAUSE_SESSION', RESUME_SESSION: 'RESUME_SESSION',
  STOP_SESSION: 'STOP_SESSION', GET_SNAPSHOT: 'GET_SNAPSHOT', CLEAR_LOG: 'CLEAR_LOG',
  MASTER_PAUSE: 'MASTER_PAUSE', MASTER_RESUME: 'MASTER_RESUME',
  PREVIEW_PORTABLE_PROFILE: 'PREVIEW_PORTABLE_PROFILE',
  IMPORT_PORTABLE_PROFILE: 'IMPORT_PORTABLE_PROFILE',
  EXPORT_PORTABLE_PROFILE: 'EXPORT_PORTABLE_PROFILE'
});
